/* global getAssetRegistry */

// Note: this has been generated by the Yeoman template and has been upgraded to ES6

/**
 * Sample transaction
 * @param {org.acme.enginesupplychain.ChangeAssetValue} changeAssetValue
 * @transaction
 */
async function onChangeAssetValue(changeAssetValue) { // eslint-disable-line no-unused-vars
    const assetRegistry = await getAssetRegistry('org.acme.enginesupplychain.SampleAsset')
    const id = changeAssetValue.relatedAsset.assetId
    const asset = await assetRegistry.get(id)

    asset.value = changeAssetValue.newValue
    await assetRegistry.update(asset)
}
